# =========================================================================
#     This makefile was generated by
#     Bakefile 0.1.8 (http://bakefile.sourceforge.net)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# C++ compiler 
CXX = g++

# Standard flags for C++ 
CXXFLAGS = 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS = 

# Standard linker flags 
LDFLAGS =  -mwindows

WINDRES = windres.exe

# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD
BOA3DEDITOR_CXXFLAGS = -I"c:\Dev-Cpp\include" -O2 -mthreads -Wall \
	-Wno-ctor-dtor-privacy $(CPPFLAGS) $(CXXFLAGS)
BOA3DEDITOR_OBJECTS =  \
	BoA3DEditor_BlAEditor.o \
	BoA3DEditor_BlAFileio.o \
	BoA3DEditor_CMemStream.o \
	BoA3DEditor_DibEngine.o \
	BoA3DEditor_dlogtool.o \
	BoA3DEditor_EdFcns.o \
	BoA3DEditor_EdGlobal.o \
	BoA3DEditor_EdParser.o \
	BoA3DEditor_EdUtils.o \
	BoA3DEditor_Graphics.o \
	BoA3DEditor_Graphutl.o \
	BoA3DEditor_keydlgs.o \
	BoA3DEditor_Library.o \
	BoA3DEditor_sound.o \
	BoA3DEditor_stdafx.o \
	BoA3DEditor_townout.o \
	BoA3DEditor_Blscened.res

### Conditionally set variables: ###



### Targets: ###

all: BoA3DEditor

install: all

uninstall: 

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f BoA3DEditor

BoA3DEditor: $(BOA3DEDITOR_OBJECTS)
	$(CXX) -o $@ $(BOA3DEDITOR_OBJECTS) $(LDFLAGS) -L"c:\Dev-Cpp\lib" -L"c:\wx\msw_build\lib" -mthreads -Wl -lgdi32 -lwinmm -lComdlg32

BoA3DEditor_BlAEditor.o: ./BlAEditor.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_BlAFileio.o: ./BlAFileio.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_CMemStream.o: ./CMemStream.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_DibEngine.o: ./DibEngine.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_dlogtool.o: ./dlogtool.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_EdFcns.o: ./EdFcns.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_EdGlobal.o: ./EdGlobal.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_EdParser.o: ./EdParser.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_EdUtils.o: ./EdUtils.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_Graphics.o: ./Graphics.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_Graphutl.o: ./Graphutl.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_keydlgs.o: ./keydlgs.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_Library.o: ./Library.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_sound.o: ./sound.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_stdafx.o: ./stdafx.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_townout.o: ./townout.cpp
	$(CXX) -c -o $@ $(BOA3DEDITOR_CXXFLAGS) $(CPPDEPS) $<

BoA3DEditor_Blscened.res: Blscened.rc 
	$(WINDRES) -i Blscened.rc --input-format=rc -o BoA3DEditor_Blscened.res -O coff 

.PHONY: all install uninstall clean


# Dependencies tracking:
-include ./*.d
